tab_title: CTF Welcome
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
title: Launch Your <span class="highlight-title">CTF</span> Challenge
typing_text: welcome to the ultimate battleground of cybersecurity!

email: kilar20@student.sdu.dk
github_username: KianBankeLarsen
codepen_username:
dev_username:
twitter_username:
linkedin_username: kilar

introduction_show_card: true
henrik_backend_host: $DEPLOYER_HOST
grafana_url: $GRAFANA_URL
keycloak_url: $KEYCLOAK_URL
ctfd_url: $CTFD_URL

building_show_card: true

api_show_card: true

ssh_show_card: true
ssh_step_ca_host: $STEP_CA_HOST
ssh_step_ca_fingerprint: $CA_FINGERPRINT
bastion_host: $BASTION_HOST
ssh_ca-pub-cert: $SSH_PUB_CERT

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]